-- Criar o banco de dados
CREATE DATABASE bancovale;

-- criando as tabelas do bancovale

CREATE TABLE beneficiario
(beneficiarioID INTEGER PRIMARY KEY NOT NULL auto_increment, nome CHAR(255) NOT NULL, dataDeNascimento DATE NOT NULL, sexo CHAR(1) NOT NULL);

CREATE TABLE medico
(medicoID INTEGER PRIMARY KEY NOT NULL auto_increment, nome CHAR(255) NOT NULL, crm CHAR (14) NOT NULL, dataDeNascimento DATE NOT NULL);

CREATE TABLE especialidade
(especialidadeID INTEGER PRIMARY KEY NOT NULL auto_increment, especialidade VARCHAR(50) NOT NULL, cbos CHAR(10) NOT NULL);

CREATE TABLE procedimento
(procedimentoID INTEGER PRIMARY KEY NOT NULL auto_increment, descricaoProcedimento VARCHAR(255) NOT NULL, TipoDeProcedimento VARCHAR (100) NOT NULL);

CREATE TABLE localAtendimento
(localID INTEGER PRIMARY KEY NOT NULL auto_increment, endereco VARCHAR(130) NOT NULL, medicoID_F INTEGER NOT NULL, especialidadeID_F INTEGER NOT NULL);

CREATE TABLE atendimentoMedico
(beneficiarioID_F INTEGER, especialidadeID_F INTEGER, medicoID_F INTEGER, localID_F INTEGER , procedimentoID_F INTEGER, data DATE);

-- criando chaves estrangeiras

ALTER TABLE localAtendimento ADD CONSTRAINT fk_medicoID_L FOREIGN KEY(medicoID_F) REFERENCES medico (medicoID);
ALTER TABLE localAtendimento ADD CONSTRAINT fk_especialidadeID_L FOREIGN KEY(especialidadeID_F) REFERENCES especialidade (especialidadeID);

ALTER TABLE atendimentoMedico ADD CONSTRAINT fk_beneficiarioID_A FOREIGN KEY(beneficiarioID_F) REFERENCES beneficiario (beneficiarioID);
ALTER TABLE atendimentoMedico ADD CONSTRAINT fk_especialidadeID_A FOREIGN KEY(especialidadeID_F) REFERENCES especialidade (especialidadeID);
ALTER TABLE atendimentoMedico ADD CONSTRAINT fk_medicoID_A FOREIGN KEY(medicoID_F) REFERENCES medico (medicoID);
ALTER TABLE atendimentoMedico ADD CONSTRAINT fk_localID_A FOREIGN KEY(localID_F) REFERENCES localAtendimento (localID);
ALTER TABLE atendimentoMedico ADD CONSTRAINT fk_procedimentoID_A FOREIGN KEY(procedimentoID_F) REFERENCES procedimento (procedimentoID);

-- Cargas de dados

INSERT INTO beneficiario VALUES ('1','ANDRE DA COSTA PASSOS','2015-03-02','M');
INSERT INTO beneficiario VALUES ('2','ANDRE DOMINGUES','2022-09-01','M');
INSERT INTO beneficiario VALUES ('3','ANDRÉ DUARTE LOPES','2022-06-01','M');
INSERT INTO beneficiario VALUES ('4','ANDRE FONSECA DI SPIRITO','2023-05-25','M');
INSERT INTO beneficiario VALUES ('5','ANDRE GLATT','2018-01-01','M');
INSERT INTO beneficiario VALUES ('6','ANDRE GONÇALVES DA SILVA','2019-02-01','M');
INSERT INTO beneficiario VALUES ('7','ANDRE LUCIO DE FRANÇA','2019-10-10','M');
INSERT INTO beneficiario VALUES ('8','ANDRÉ LUIZ ARAÚJO TEIXEIRA','2021-05-01','M');
INSERT INTO beneficiario VALUES ('9','ANDRE LUIZ DA COSTA VICENTE','2022-04-01','M');
INSERT INTO beneficiario VALUES ('10','ANDRE LUIZ DA SILVA DAMASCENO','2021-01-01','M');
INSERT INTO beneficiario VALUES ('11','ANDRE LUIZ DOS SANTOS BELLONI','2007-03-16','M');
INSERT INTO beneficiario VALUES ('12','ANDRE LUIZ FONSECA ALVES','1985-03-21','M');
INSERT INTO beneficiario VALUES ('13','ANDRE LUIZ FREITAS BASTIANA','2022-11-01','M');
INSERT INTO beneficiario VALUES ('14','ANDRE LUIZ MONTEIRO RODRIGUES','2023-05-01','M');
INSERT INTO beneficiario VALUES ('15','ANDRE LUIZ RAMOS DE SOUZA','2018-09-20','M');
INSERT INTO beneficiario VALUES ('16','ANDRE SAMPAIO SANTOS','2017-01-01','M');
INSERT INTO beneficiario VALUES ('17','ANDRE STEFANO BUENO VIEIRA','2021-06-07','M');
INSERT INTO beneficiario VALUES ('18','ANDRE VINICIUS AZEVEDO DA SILVA','2018-08-31','M');
INSERT INTO beneficiario VALUES ('19','ANDREA APARECIDA FRANKLIN DE BRITO','2023-05-01','F');
INSERT INTO beneficiario VALUES ('20','ANDREA DE ARAUJO CASSA','2022-10-03','F');
INSERT INTO beneficiario VALUES ('21','ANDREA DE ARAUJO NOGUEIRA','2018-08-27','F');
INSERT INTO beneficiario VALUES ('22','ANDREA LUCIA COELHO','2017-01-01','F');
INSERT INTO beneficiario VALUES ('23','ANDREA VIANNA PARR LOPES','2009-09-23','F');
INSERT INTO beneficiario VALUES ('24','ANDREA VIRGINIA RODRIGUES PENNA','1987-11-01','F');
INSERT INTO beneficiario VALUES ('25','ANDREIA AGRESTA CORREA','2015-06-26','F');
INSERT INTO beneficiario VALUES ('26','ANDREIA CRISTINA REZENDE MARINHO DE SOUZA','2019-01-01','F');
INSERT INTO beneficiario VALUES ('27','ANDREIA FERREIRA DE MENEZES LIMA','2021-01-01','F');
INSERT INTO beneficiario VALUES ('28','ANDRESSA CRISTINA TAKETA DE LIMA','2015-03-02','F');
INSERT INTO beneficiario VALUES ('29','ANDRESSA DOS SANTOS TAVEIRA AMADOR','2023-07-01','F');
INSERT INTO beneficiario VALUES ('30','ANDREY DE PAIVA TEIXEIRA','2023-01-01','F');
INSERT INTO beneficiario VALUES ('31','ANDREZA CRISTINA REIS ALVES GASPAR','2021-09-15','F');
INSERT INTO beneficiario VALUES ('32','ANDREZZA NAIR TEIXEIRA BORGES FERREIRA','2021-01-01','F');
INSERT INTO beneficiario VALUES ('33','ANETE RIBEIRO LESSA','2018-04-01','F');
INSERT INTO beneficiario VALUES ('34','ANGELA CRISTINA DE O. C. DE ALCANTARA','2020-04-01','F');
INSERT INTO beneficiario VALUES ('35','ANGELA DOS SANTOS CARNEIRO','2023-07-01','F');
INSERT INTO beneficiario VALUES ('36','ANGELA MARIA RIBEIRO DE ALMEIDA LEMOS','1985-04-10','F');
INSERT INTO beneficiario VALUES ('37','ANGELA NERES DE CASTRO LOPES','2018-04-05','F');
INSERT INTO beneficiario VALUES ('38','ANGELINA CONCEIÇÃO DE JESUS BRAGA','2018-02-08','F');
INSERT INTO beneficiario VALUES ('39','ANGELINA DE BARROS FERREIRA','2015-07-01','F');
INSERT INTO beneficiario VALUES ('40','ANGELITA SERRA VALLADÃO','2019-02-01','F');
INSERT INTO beneficiario VALUES ('41','ANNA CECILIA FARO BONAN','2023-02-02','F');
INSERT INTO beneficiario VALUES ('42','ANNA LUIZA GAUDINI DE OLIVEIRA','2021-05-01','F');
INSERT INTO beneficiario VALUES ('43','ANNA PAULA DOS SANTOS COSENZA RIBEIRO','2023-02-02','F');
INSERT INTO beneficiario VALUES ('44','ANNA RAPHAELA CORREA CANDIDO','2015-03-02','F');
INSERT INTO beneficiario VALUES ('45','ANTHONY YURI GATTO','2018-08-27','M');
INSERT INTO beneficiario VALUES ('46','ANTONIO CALADO DOS SANTOS','2010-08-26','M');
INSERT INTO beneficiario VALUES ('47','ANTONIO CARLOS ABREU DE AZEVEDO','1987-03-16','M');
INSERT INTO beneficiario VALUES ('48','ANTONIO CARLOS DE ALVARENGA RIBEIRO','1987-03-16','M');
INSERT INTO beneficiario VALUES ('49','ANTONIO CARLOS GOMES XAVIER','2022-09-01','M');
INSERT INTO beneficiario VALUES ('50','ANTONIO CARLOS SANTOS GONCALVES','2023-02-01','M');
INSERT INTO beneficiario VALUES ('51','ANTONIO CARLOS TITO MORENO','2020-08-01','M');
INSERT INTO beneficiario VALUES ('52','ANTONIO CESAR LINS CAVALCANTI','2021-01-01','M');
INSERT INTO beneficiario VALUES ('53','ANTONIO CORNELIO COSTA','1985-03-25','M');
INSERT INTO beneficiario VALUES ('54','ANTONIO DE ALBUQUERQUE DI CARLO','1986-08-14','M');
INSERT INTO beneficiario VALUES ('55','ANTÔNIO ELIESIO DAMÁZIO DO NASCIMENTO','2021-01-01','M');
INSERT INTO beneficiario VALUES ('56','ANTONIO GASPAR DE GOUVEIA','2013-01-01','M');
INSERT INTO beneficiario VALUES ('57','ANTONIO HENRIQUE DE PAULA LOPES BRANDAO','2023-02-01','M');
INSERT INTO beneficiario VALUES ('58','ANTÔNIO HIGINO DA COSTA','2019-02-01','M');
INSERT INTO beneficiario VALUES ('59','ANTONIO JORGE SIMOA DE SOUZA','2022-11-01','M');
INSERT INTO beneficiario VALUES ('60','ANTONIO JOSE DE ARAUJO','1987-11-01','M');
INSERT INTO beneficiario VALUES ('61','ANTÔNIO LUIZ DA SILVA MOREIRA','1985-04-23','M');
INSERT INTO beneficiario VALUES ('62','ANTONIO MARIA FERNANDES PACHECO','2022-02-18','M');
INSERT INTO beneficiario VALUES ('63','ANTÔNIO MÁRIO CARVALHO E SILVA','2021-04-29','M');
INSERT INTO beneficiario VALUES ('64','ANTONIO MAURICIO MODESTO RAINHO','2023-02-09','M');
INSERT INTO beneficiario VALUES ('65','ANTONIO MAURICIO XAVIER','1985-03-22','M');
INSERT INTO beneficiario VALUES ('66','ANTONIO MOLISANI','2016-04-28','M');
INSERT INTO beneficiario VALUES ('67','ANTONIO PASCOAL DA SILVA','1985-03-22','M');
INSERT INTO beneficiario VALUES ('68','ANTONIO PAULO DA CONCEIÇÃO','1987-11-01','M');
INSERT INTO beneficiario VALUES ('69','ANTONIO PEDRO CAMPELLO PEREIRA PORTO SOARES','2023-05-10','M');
INSERT INTO beneficiario VALUES ('70','ANTONIO RODRIGUES DE OLIVEIRA','2012-02-02','M');
INSERT INTO beneficiario VALUES ('71','ANTONIO VENANCIO GUSMAO','1987-11-01','M');
INSERT INTO beneficiario VALUES ('72','ANTONIO VICENTE PORPHIRIO','1987-11-01','M');
INSERT INTO beneficiario VALUES ('73','APARECIDA LOYOLLA CORREA','2023-02-02','F');
INSERT INTO beneficiario VALUES ('74','ARACELI AFONSO THEODORO','1996-06-10','F');
INSERT INTO beneficiario VALUES ('75','ARAGUACI SILVA DO CARMO','2017-06-22','F');
INSERT INTO beneficiario VALUES ('76','ARLEI DE LOURIVAL ASSUCENA','2023-01-01','F');
INSERT INTO beneficiario VALUES ('77','ARMANDO BRITTES MONTEIRO','2015-03-02','M');
INSERT INTO beneficiario VALUES ('78','ARTHUR MARCELO GUIMARÃES CARVALHO','2021-05-01','M');
INSERT INTO beneficiario VALUES ('79','ARTHUR PEREIRA DE LIMA NETO','1987-03-16','M');
INSERT INTO beneficiario VALUES ('80','ARTUR EDUARDO DOS SANTOS MENDOZA','1987-03-16','M');
INSERT INTO beneficiario VALUES ('81','ARTUR JUNQUEIRA DE ALMEIDA','2017-05-01','M');
INSERT INTO beneficiario VALUES ('82','ARY PEREIRA LEITE FILHO','2023-06-21','M');
INSERT INTO beneficiario VALUES ('83','ARY TAVARES ALVES JUNIOR','2021-09-01','M');
INSERT INTO beneficiario VALUES ('84','AURIMAR SILVA REIS','2023-06-01','M');
INSERT INTO beneficiario VALUES ('85','AYLA PAIVA DA SILVA ROUBERT','2023-02-01','F');
INSERT INTO beneficiario VALUES ('86','AYMEE NUNES NORONHA','1987-03-16','F');
INSERT INTO beneficiario VALUES ('87','BARBARA CRISTINA MARTINS LOPES DE OLIVEIRA','2021-01-01','F');
INSERT INTO beneficiario VALUES ('88','BARBARA CRISTINA MARTINS TEIXEIRA ZACCARO','2023-07-01','F');
INSERT INTO beneficiario VALUES ('89','BARBARA LUCIA JOAQUIM SALES','2021-01-01','F');
INSERT INTO beneficiario VALUES ('90','BEATRIZ DA SILVA COUTO','2023-07-01','F');
INSERT INTO beneficiario VALUES ('91','BEATRIZ GOLDENBERG KITOBER','2021-03-01','F');
INSERT INTO beneficiario VALUES ('92','BEATRIZ MORAES BRANDAO','2021-01-01','F');
INSERT INTO beneficiario VALUES ('93','BECHARA JORIS THEME NETO','1987-03-16','F');
INSERT INTO beneficiario VALUES ('94','BELGENISIA ALVES CHAVES','1987-12-14','F');
INSERT INTO beneficiario VALUES ('95','BENITO FRANCISCO MARSILI FILHO','1987-12-14','M');
INSERT INTO beneficiario VALUES ('96','BERNARDO MARGULIES CAVALCANTI','2018-08-27','M');
INSERT INTO beneficiario VALUES ('97','BIANCA DE SOUSA ANTUNES','2021-01-01','F');
INSERT INTO beneficiario VALUES ('98','BIANCA MARIA ALMEIDA MARTINS','2018-09-11','F');
INSERT INTO beneficiario VALUES ('99','BIANCA MARIA CASTRO VIANNA','2012-02-24','F');
INSERT INTO beneficiario VALUES ('100','BIANCA MENEZES RODRIGUES AMPARO','2014-10-01','F');
INSERT INTO beneficiario VALUES ('101','BIANCA NOVAES DE MELLO LIMA','2023-06-01','F');
INSERT INTO beneficiario VALUES ('102','BIANCA RODRIGUES TOLEDO','2023-02-01','F');
INSERT INTO beneficiario VALUES ('103','BIANCA SÃO LUIZ PACHECO AZEVEDO','2021-01-05','F');
INSERT INTO beneficiario VALUES ('104','BRENDA STEFFANI MARQUES PEREIRA','2023-02-02','F');
INSERT INTO beneficiario VALUES ('105','BRENO BORTOLOTTI BATISTA','2016-04-28','M');
INSERT INTO beneficiario VALUES ('106','BRENO RICARDO RIBEIRO DE ARRUDA','2013-01-01','M');
INSERT INTO beneficiario VALUES ('107','BRENO SABOIA SAEGER','2022-11-01','M');


INSERT INTO medico VALUES ('1','BRUNA CELY DE ALMEIDA','3569','2022-08-23');
INSERT INTO medico VALUES ('2','BRUNA DESTRO BATISTA','4348','2015-03-02');
INSERT INTO medico VALUES ('3','BRUNA GOMES LEÃO DE DECCO SOARES','11374','2018-07-01');
INSERT INTO medico VALUES ('4','BRUNO CARLOS FERRARO DE MENEZES','5290','2023-07-01');
INSERT INTO medico VALUES ('5','BRUNO CESAR DE CARVALHO COELHO','4767','2015-03-27');
INSERT INTO medico VALUES ('6','BRUNO CORREA BASTOS','1925','1987-11-01');
INSERT INTO medico VALUES ('7','BRUNO DE SOUSA CARVALHO','11669','2018-08-29');
INSERT INTO medico VALUES ('8','BRUNO LEITE MOZER','4390','2015-03-02');
INSERT INTO medico VALUES ('9','BRUNO MARTINS GONÇALVES','484','2021-01-01');
INSERT INTO medico VALUES ('10','BRUNO PEREIRA GUERRA','10753','2018-03-05');
INSERT INTO medico VALUES ('11','BRUNO RUMMERT CARNEIRO','4621','2023-02-01');
INSERT INTO medico VALUES ('12','BRUNO SADOCK MATOS DE OLIVEIRA','5200','2021-08-17');
INSERT INTO medico VALUES ('13','BRUNO SOUZA CROPALATO DE ARAUJO','11636','2018-09-03');
INSERT INTO medico VALUES ('14','CAIO CESAR DA SILVA PALMA','4540','2023-02-09');
INSERT INTO medico VALUES ('15','CAIO OLIVEIRA DA SILVA','5707','2023-07-01');
INSERT INTO medico VALUES ('16','CAIUS SARCIA ROCHA','1085','2021-02-01');
INSERT INTO medico VALUES ('17','CAMILA ALMEIDA DA SILVA','4375','2015-03-02');
INSERT INTO medico VALUES ('18','CAMILA DA SILVA','5345','2023-07-01');
INSERT INTO medico VALUES ('19','CAMILA DE SOUZA DOS SANTOS','384','2021-01-01');
INSERT INTO medico VALUES ('20','CAMILA PARADA DOS SANTOS ALMEIDA','14338','2020-10-08');
INSERT INTO medico VALUES ('21','CAMILA PEREIRA DE ALBUQUERQUE FERREIRA','3649','2022-09-23');
INSERT INTO medico VALUES ('22','CAMILO DUQUESNOIS DUBOIS BRITO','4407','2015-03-02');
INSERT INTO medico VALUES ('23','CANDIDO TEIXEIRA LOPES NETO','4862','2019-06-10');
INSERT INTO medico VALUES ('24','CARINA DUARTE SUÁREZ DOS SANTOS','976','2021-01-01');
INSERT INTO medico VALUES ('25','CARINE LEIS DE OLIVEIRA','4729','2023-02-01');
INSERT INTO medico VALUES ('26','CARLA ALVES MIRANDA LOPES DA SILVA','4125','2023-01-01');
INSERT INTO medico VALUES ('27','CARLA CALVET CORREA DE OLIVEIRA','4400','2015-03-02');
INSERT INTO medico VALUES ('28','CARLA CELESTINO COSTA','1983','2021-06-01');
INSERT INTO medico VALUES ('29','CARLA SCOFANO','11625','2018-09-03');
INSERT INTO medico VALUES ('30','CARLINDA DE LIMA XAVIER','321','1986-01-01');
INSERT INTO medico VALUES ('31','CARLO ROBERTO SIMI','1651','2021-05-01');
INSERT INTO medico VALUES ('32','CARLOS AFFONSO LEONY NETO','2562','2021-10-01');
INSERT INTO medico VALUES ('33','CARLOS ALBERTO CARNELOS BARBOZA','153','1987-11-01');
INSERT INTO medico VALUES ('34','CARLOS ALBERTO DE CAMPOS MARQUES','13932','2020-04-01');
INSERT INTO medico VALUES ('35','CARLOS ALBERTO GOMES DE ARAUJO','325','1987-03-16');
INSERT INTO medico VALUES ('36','CARLOS HENRIQUE SILVA DOS SANTOS','11733','2018-09-20');
INSERT INTO medico VALUES ('37','CARLOS JOSE COUTINHO GONÇALVES','4595','1987-03-16');
INSERT INTO medico VALUES ('38','CARLOS JOSE DE SOUZA','260','1987-03-16');
INSERT INTO medico VALUES ('39','CARLOS JOSÉ FERREIRA DE ABREU E LIMA','1228','2021-03-01');
INSERT INTO medico VALUES ('40','CARLOS LUIZ CESARIO JUNIOR','10624','2018-01-18');
INSERT INTO medico VALUES ('41','CARLOS MOURA DA CRUZ','5695','2023-07-01');
INSERT INTO medico VALUES ('42','CARLOS TORRES DE MACEDO COSTA','2032','1987-11-01');
INSERT INTO medico VALUES ('43','CARLOS WALLACE CORREA DE HOLANDA','964','2021-01-01');
INSERT INTO medico VALUES ('44','CARMEN BOTTINO RUA','274','1991-01-28');
INSERT INTO medico VALUES ('45','CARMEN LUCIA FERREIRA DA SILVA','11941','2016-03-01');
INSERT INTO medico VALUES ('46','CAROLINA AIRES MUCCILLO','1967','2021-06-07');
INSERT INTO medico VALUES ('47','CAROLINA BRAGA LEITE TAVARES','6205','2016-04-28');
INSERT INTO medico VALUES ('48','CAROLINA DA SILVA BENSINO','11661','2018-09-05');
INSERT INTO medico VALUES ('49','CAROLINA LIMA MACEDO DE ALMEIDA','4361','2015-04-14');
INSERT INTO medico VALUES ('50','CAROLINA SILVA OLIVEIRA CEREJA','4062','2023-01-01');
INSERT INTO medico VALUES ('51','CAROLINE DE SOUZA SILVESTRE','6166','2016-04-29');
INSERT INTO medico VALUES ('52','CAROLINE RODRIGUES DE ANDRADE','6164','2016-04-28');
INSERT INTO medico VALUES ('53','CAROLINE SOUZA DE CASTRO','4429','2023-02-02');
INSERT INTO medico VALUES ('54','CASSIA MARIA LIMA BORJA','5271','2015-07-08');
INSERT INTO medico VALUES ('55','CASSIANE TAVARES MACIEL','4985','2023-04-01');
INSERT INTO medico VALUES ('56','CATARINA ELIAS JACOB MATTAR','417','1987-03-16');
INSERT INTO medico VALUES ('57','CATIA CILENE ESTEVAO DA CUNHA MENDONÇA','6427','2023-06-26');
INSERT INTO medico VALUES ('58','CATIA DE SOUZA NOGUEIRA DE PAIVA','2097','2021-07-02');
INSERT INTO medico VALUES ('59','CATIA LEA PEREIRA DE ALVARENGA','2749','2022-02-01');
INSERT INTO medico VALUES ('60','CECILIA PAIM VARELLA','5190','2015-08-05');
INSERT INTO medico VALUES ('61','CELENE APARECIDA BOTELHO VALENTIM','4462','2023-02-02');
INSERT INTO medico VALUES ('62','CELIA DA SILVA MATTOS MONTEIRO','589','1987-11-01');
INSERT INTO medico VALUES ('63','CELIA MARIA BAPTISTA DE ARAUJO','420','1987-03-16');
INSERT INTO medico VALUES ('64','CELIA MARIA NICOLA','298','1987-11-01');
INSERT INTO medico VALUES ('65','CELIA REGINA BOTELHO DE SOUZA','1897','1987-11-01');
INSERT INTO medico VALUES ('66','CELIA REGINA DA SILVA VIANA','5128','2023-06-01');
INSERT INTO medico VALUES ('67','CELINA MARIA PAIVA DE ARAUJO','1983','1987-12-29');
INSERT INTO medico VALUES ('68','CELINE MARTINS DA SILVA','4414','2023-02-02');
INSERT INTO medico VALUES ('69','CELIO FERNANDO GARCEZ SERQUEIRA','1494','2021-04-01');
INSERT INTO medico VALUES ('70','CELIO ROBERTO SERRAT FELIX','4936','2023-04-01');
INSERT INTO medico VALUES ('71','CELSO VALENTIM MENDES DA COSTA','946','1985-08-23');
INSERT INTO medico VALUES ('72','CESAR AUGUSTO DE CARVALHO SIMÕES','4064','2023-01-01');
INSERT INTO medico VALUES ('73','CESAR CARDOSO LOPES','4362','2023-02-01');
INSERT INTO medico VALUES ('74','CESAR RODRIGUES ABRAHAO','2724','2014-01-01');
INSERT INTO medico VALUES ('75','CÉU SILVA CAVALCANTI','4445','2023-02-02');
INSERT INTO medico VALUES ('76','CHARLOTTE CASTELLO BRANCO JONQUA','5185','2015-08-14');
INSERT INTO medico VALUES ('77','CHIRLEI MATOS SANTOS','6193','2016-05-23');
INSERT INTO medico VALUES ('78','CHRISTIAN DOS SANTOS SILVA','11582','2018-09-10');
INSERT INTO medico VALUES ('79','CHRISTIANE EIRAS FERREIRA DA SILVA','3612','2000-05-12');
INSERT INTO medico VALUES ('80','CHRISTIANE PEREIRA TOSTA','519','2011-06-13');
INSERT INTO medico VALUES ('81','CICERO PEREIRA RODRIGUES','153','1985-03-29');
INSERT INTO medico VALUES ('82','CICILIA DE JESUS AVELINO FERREIRA','11759','2018-09-27');
INSERT INTO medico VALUES ('83','CINALDO JOSÉ DO ROZÁRIO PIRES','2814','2022-03-01');
INSERT INTO medico VALUES ('84','CINTIA FEIJÓ GUIMARÃES COSTA','997','2021-01-14');
INSERT INTO medico VALUES ('85','CINTIA LETICIA FERNANDES DA SILVA','11588','2018-09-12');
INSERT INTO medico VALUES ('86','CINTIA RIBEIRO','13723','2020-01-21');
INSERT INTO medico VALUES ('87','CINTYA LINS DE SOUZA','4591','2023-02-02');
INSERT INTO medico VALUES ('88','CLADIR FERREIRA DE SOUZA','1985','1987-11-01');
INSERT INTO medico VALUES ('89','CLARICE PEREIRA LIMA GREEN','4491','2023-02-02');
INSERT INTO medico VALUES ('90','CLARISSA BRANDÃO DE ARAUJO LOPES','6162','2016-04-29');
INSERT INTO medico VALUES ('91','CLARISSA LOPES VIEIRA ALVES DA CUNHA','415','2021-01-01');
INSERT INTO medico VALUES ('92','CLAUDIA BUSTAMANTE LEVY','11619','2018-09-10');
INSERT INTO medico VALUES ('93','CLAUDIA CARVALHO LIMA FEITAL','4416','2023-02-02');
INSERT INTO medico VALUES ('94','CLAUDIA DE OLIVEIRA CABRAL SANTOS','357','1987-12-01');
INSERT INTO medico VALUES ('95','CLAUDIA DIAS VENTURA QUINTANILHA','1876','1987-11-01');
INSERT INTO medico VALUES ('96','CLAUDIA DOS ANJOS PACHECO DE CASTRO','5211','2023-06-01');
INSERT INTO medico VALUES ('97','CLAUDIA LUCIA CAETANO DE ARAUJO','342','1996-06-10');
INSERT INTO medico VALUES ('98','CLAUDIA MARINHO MATOS DO VALE','333','2021-01-01');
INSERT INTO medico VALUES ('99','CLAUDIA PALOMA MAGALHÃES PRADO','11278','2021-01-21');
INSERT INTO medico VALUES ('100','CLAUDIA PARANHOS FARIA','2029','1987-11-01');
INSERT INTO medico VALUES ('101','CLAUDIA REGINA MATOS DOS SANTOS FERREIRA','1984','1987-12-11');
INSERT INTO medico VALUES ('102','CLAUDIA REGINA RIBEIRO BRAZ','9733','2017-04-01');
INSERT INTO medico VALUES ('103','CLAUDIA RIVOLLI THOMAS DE SA','2109','1997-11-13');
INSERT INTO medico VALUES ('104','CLAUDIA VICCHETTI FERREIRA DE SOUSA','679','2021-01-05');
INSERT INTO medico VALUES ('105','CLAUDIO AMARAL AZZI','429','2021-01-11');
INSERT INTO medico VALUES ('106','CLAUDIO BENEVENUTE LOZANA','6200','2017-09-11');
INSERT INTO medico VALUES ('107','CLAUDIO DIAS LOPES','303','1987-11-01');
INSERT INTO medico VALUES ('108','CLAUDIO GONZAGA DE CARVALHO','1341','2021-03-01');


INSERT INTO especialidade VALUES ('1','Cirurgião dentista - auditor','223204');
INSERT INTO especialidade VALUES ('2','Cirurgião dentista - clínico geral','223208');
INSERT INTO especialidade VALUES ('3','Cirurgião dentista - endodontista','223212');
INSERT INTO especialidade VALUES ('4','Cirurgião dentista - epidemiologista','223216');
INSERT INTO especialidade VALUES ('5','Cirurgião dentista - estomatologista','223220');
INSERT INTO especialidade VALUES ('6','Cirurgião dentista - implantodontista','223224');
INSERT INTO especialidade VALUES ('7','Cirurgião dentista - odontogeriatra','223228');
INSERT INTO especialidade VALUES ('8','Cirurgião dentista - odontologista legal','223232');
INSERT INTO especialidade VALUES ('9','Cirurgião dentista - odontopediatra','223236');
INSERT INTO especialidade VALUES ('10','Cirurgião dentista - ortopedista e ortodontista','223240');
INSERT INTO especialidade VALUES ('11','Cirurgião dentista - patologista bucal','223244');
INSERT INTO especialidade VALUES ('12','Cirurgião dentista - periodontista','223248');
INSERT INTO especialidade VALUES ('13','Cirurgião dentista - protesiólogo bucomaxilofacial','223252');
INSERT INTO especialidade VALUES ('14','Cirurgião dentista - protesista','223256');
INSERT INTO especialidade VALUES ('15','Cirurgião dentista - radiologista','223260');
INSERT INTO especialidade VALUES ('16','Cirurgião dentista - reabilitador oral','223264');
INSERT INTO especialidade VALUES ('17','Cirurgião dentista - traumatologista bucomaxilofacial','223268');
INSERT INTO especialidade VALUES ('18','Cirurgião dentista de saúde coletiva','223272');
INSERT INTO especialidade VALUES ('19','Cirurgião dentista - odontologia do trabalho','223276');
INSERT INTO especialidade VALUES ('20','Cirurgião dentista - dentística','223280');
INSERT INTO especialidade VALUES ('21','Cirurgião dentista - disfunção temporomandibular e dor orofacial','223284');
INSERT INTO especialidade VALUES ('22','Cirurgião dentista - odontologia para pacientes com necessidades especiais','223288');
INSERT INTO especialidade VALUES ('23','Cirurgião-dentista da estratégia de saúde da família','223293');
INSERT INTO especialidade VALUES ('24','Médico veterinário','223305');
INSERT INTO especialidade VALUES ('25','Zootecnista','223310');
INSERT INTO especialidade VALUES ('26','Farmacêutico','223405');
INSERT INTO especialidade VALUES ('27','Farmacêutico analista clínico','223415');
INSERT INTO especialidade VALUES ('28','Farmacêutico de alimentos','223420');
INSERT INTO especialidade VALUES ('29','Farmacêutico práticas integrativas e complementares','223425');
INSERT INTO especialidade VALUES ('30','Farmacêutico em saúde pública','223430');
INSERT INTO especialidade VALUES ('31','Farmacêutico industrial','223435');
INSERT INTO especialidade VALUES ('32','Farmacêutico toxicologista','223440');
INSERT INTO especialidade VALUES ('33','Farmacêutico hospitalar e clínico','223445');
INSERT INTO especialidade VALUES ('34','Enfermeiro','223505');
INSERT INTO especialidade VALUES ('35','Enfermeiro auditor','223510');
INSERT INTO especialidade VALUES ('36','Enfermeiro de bordo','223515');
INSERT INTO especialidade VALUES ('37','Enfermeiro de centro cirúrgico','223520');
INSERT INTO especialidade VALUES ('38','Enfermeiro de terapia intensiva','223525');
INSERT INTO especialidade VALUES ('39','Enfermeiro do trabalho','223530');
INSERT INTO especialidade VALUES ('40','Enfermeiro nefrologista','223535');
INSERT INTO especialidade VALUES ('41','Enfermeiro neonatologista','223540');
INSERT INTO especialidade VALUES ('42','Enfermeiro obstétrico','223545');
INSERT INTO especialidade VALUES ('43','Enfermeiro psiquiátrico','223550');
INSERT INTO especialidade VALUES ('44','Enfermeiro puericultor e pediátrico','223555');
INSERT INTO especialidade VALUES ('45','Enfermeiro sanitarista','223560');
INSERT INTO especialidade VALUES ('46','Enfermeiro da estratégia de saúde da família','223565');
INSERT INTO especialidade VALUES ('47','Perfusionista','223570');
INSERT INTO especialidade VALUES ('48','Obstetriz','223575');
INSERT INTO especialidade VALUES ('49','Enfermeiro estomaterapeuta','223580');
INSERT INTO especialidade VALUES ('50','Enfermeiro forense','223585');
INSERT INTO especialidade VALUES ('51','Fisioterapeuta geral','223605');
INSERT INTO especialidade VALUES ('52','Fisioterapeuta respiratória','223625');
INSERT INTO especialidade VALUES ('53','Fisioterapeuta neurofuncional','223630');
INSERT INTO especialidade VALUES ('54','Fisioterapeuta traumato-ortopédica funcional','223635');
INSERT INTO especialidade VALUES ('55','Fisioterapeuta osteopata','223640');
INSERT INTO especialidade VALUES ('56','Fisioterapeuta quiropraxista','223645');
INSERT INTO especialidade VALUES ('57','Fisioterapeuta acupunturista','223650');
INSERT INTO especialidade VALUES ('58','Fisioterapeuta esportivo','223655');
INSERT INTO especialidade VALUES ('59','Fisioterapeuta  do trabalho','223660');
INSERT INTO especialidade VALUES ('60','Dietista','223705');
INSERT INTO especialidade VALUES ('61','Nutricionista','223710');
INSERT INTO especialidade VALUES ('62','Fonoaudiólogo geral','223810');
INSERT INTO especialidade VALUES ('63','Fonoaudiólogo educacional','223815');
INSERT INTO especialidade VALUES ('64','Fonoaudiólogo em audiologia','223820');
INSERT INTO especialidade VALUES ('65','Fonoaudiólogo em disfagia','223825');
INSERT INTO especialidade VALUES ('66','Fonoaudiólogo em linguagem','223830');
INSERT INTO especialidade VALUES ('67','Fonoaudiólogo em motricidade orofacial','223835');
INSERT INTO especialidade VALUES ('68','Fonoaudiólogo em saúde coletiva','223840');
INSERT INTO especialidade VALUES ('69','Fonoaudiólogo em voz','223845');
INSERT INTO especialidade VALUES ('70','Terapeuta ocupacional','223905');
INSERT INTO especialidade VALUES ('71','Ortoptista','223910');
INSERT INTO especialidade VALUES ('72','Psicomotricista','223915');
INSERT INTO especialidade VALUES ('73','Avaliador físico','224105');
INSERT INTO especialidade VALUES ('74','Ludomotricista','224110');
INSERT INTO especialidade VALUES ('75','Preparador de atleta','224115');
INSERT INTO especialidade VALUES ('76','Preparador físico','224120');
INSERT INTO especialidade VALUES ('77','Técnico de desporto individual e coletivo (exceto futebol)','224125');
INSERT INTO especialidade VALUES ('78','Técnico de laboratório e fiscalização desportiva','224130');
INSERT INTO especialidade VALUES ('79','Treinador profissional de futebol','224135');
INSERT INTO especialidade VALUES ('80','Profissional de educação física na saúde','224140');
INSERT INTO especialidade VALUES ('81','Médico infectologista','225103');
INSERT INTO especialidade VALUES ('82','Médico acupunturista','225105');
INSERT INTO especialidade VALUES ('83','Médico legista','225106');
INSERT INTO especialidade VALUES ('84','Médico nefrologista','225109');
INSERT INTO especialidade VALUES ('85','Médico alergista e imunologista','225110');
INSERT INTO especialidade VALUES ('86','Médico neurologista','225112');
INSERT INTO especialidade VALUES ('87','Médico angiologista','225115');
INSERT INTO especialidade VALUES ('88','Médico nutrologista','225118');
INSERT INTO especialidade VALUES ('89','Médico cardiologista','225120');
INSERT INTO especialidade VALUES ('90','Médico oncologista clínico','225121');
INSERT INTO especialidade VALUES ('91','Médico cancerologista pediátrico','225122');
INSERT INTO especialidade VALUES ('92','Médico pediatra','225124');
INSERT INTO especialidade VALUES ('93','Médico clínico','225125');
INSERT INTO especialidade VALUES ('94','Médico pneumologista','225127');
INSERT INTO especialidade VALUES ('95','Médico de família e comunidade','225130');
INSERT INTO especialidade VALUES ('96','Médico psiquiatra','225133');
INSERT INTO especialidade VALUES ('97','Médico dermatologista','225135');
INSERT INTO especialidade VALUES ('98','Médico reumatologista','225136');
INSERT INTO especialidade VALUES ('99','Médico sanitarista','225139');
INSERT INTO especialidade VALUES ('100','Médico do trabalho','225140');
INSERT INTO especialidade VALUES ('101','Médico da estratégia de saúde da família','225142');
INSERT INTO especialidade VALUES ('102','Médico em medicina de tráfego','225145');
INSERT INTO especialidade VALUES ('103','Médico anatomopatologista','225148');
INSERT INTO especialidade VALUES ('104','Médico em medicina intensiva','225150');
INSERT INTO especialidade VALUES ('105','Médico anestesiologista','225151');
INSERT INTO especialidade VALUES ('106','Médico antroposófico','225154');
INSERT INTO especialidade VALUES ('107','Médico endocrinologista e metabologista','225155');
INSERT INTO especialidade VALUES ('108','Médico fisiatra','225160');
INSERT INTO especialidade VALUES ('109','Médico gastroenterologista','225165');
INSERT INTO especialidade VALUES ('110','Médico generalista','225170');
INSERT INTO especialidade VALUES ('111','Médico geneticista','225175');
INSERT INTO especialidade VALUES ('112','Médico geriatra','225180');
INSERT INTO especialidade VALUES ('113','Médico hematologista','225185');
INSERT INTO especialidade VALUES ('114','Médico homeopata','225195');
INSERT INTO especialidade VALUES ('115','Médico em cirurgia vascular','225203');
INSERT INTO especialidade VALUES ('116','Médico cirurgião cardiovascular','225210');
INSERT INTO especialidade VALUES ('117','Médico cirurgião de cabeça e pescoço','225215');
INSERT INTO especialidade VALUES ('118','Médico cirurgião do aparelho digestivo','225220');
INSERT INTO especialidade VALUES ('119','Médico cirurgião geral','225225');
INSERT INTO especialidade VALUES ('120','Médico cirurgião pediátrico','225230');
INSERT INTO especialidade VALUES ('121','Médico cirurgião plástico','225235');
INSERT INTO especialidade VALUES ('122','Médico cirurgião torácico','225240');
INSERT INTO especialidade VALUES ('123','Médico ginecologista e obstetra','225250');
INSERT INTO especialidade VALUES ('124','Médico mastologista','225255');
INSERT INTO especialidade VALUES ('125','Médico neurocirurgião','225260');
INSERT INTO especialidade VALUES ('126','Médico oftalmologista','225265');
INSERT INTO especialidade VALUES ('127','Médico ortopedista e traumatologista','225270');
INSERT INTO especialidade VALUES ('128','Médico otorrinolaringologista','225275');
INSERT INTO especialidade VALUES ('129','Médico coloproctologista','225280');
INSERT INTO especialidade VALUES ('130','Médico urologista','225285');
INSERT INTO especialidade VALUES ('131','Médico cancerologista cirurgíco','225290');
INSERT INTO especialidade VALUES ('132','Médico cirurgião da mão','225295');
INSERT INTO especialidade VALUES ('133','Médico citopatologista','225305');
INSERT INTO especialidade VALUES ('134','Médico em endoscopia','225310');
INSERT INTO especialidade VALUES ('135','Médico em medicina nuclear','225315');
INSERT INTO especialidade VALUES ('136','Médico em radiologia e diagnóstico por imagem','225320');
INSERT INTO especialidade VALUES ('137','Médico patologista','225325');
INSERT INTO especialidade VALUES ('138','Médico radioterapeuta','225330');
INSERT INTO especialidade VALUES ('139','Médico patologista clínico / medicina laboratorial','225335');
INSERT INTO especialidade VALUES ('140','Médico hemoterapeuta','225340');
INSERT INTO especialidade VALUES ('141','Médico hiperbarista','225345');
INSERT INTO especialidade VALUES ('142','Médico neurofisiologista clínico','225350');
INSERT INTO especialidade VALUES ('143','Médico radiologista intervencionista','225355');
INSERT INTO especialidade VALUES ('144','Quiropraxista','226105');
INSERT INTO especialidade VALUES ('145','Osteopata','226110');
INSERT INTO especialidade VALUES ('146','Musicoterapeuta','226305');
INSERT INTO especialidade VALUES ('147','Arteterapeuta','226310');
INSERT INTO especialidade VALUES ('148','Equoterapeuta','226315');
INSERT INTO especialidade VALUES ('149','Naturólogo','226320');


INSERT INTO procedimento VALUES ('1','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('2','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('3','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('4','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('5','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('6','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('7','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('8','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('9','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('10','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('11','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('12','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('13','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('14','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('15','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('16','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('17','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('18','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('19','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('20','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('21','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('22','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('23','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('24','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('25','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('26','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('27','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('28','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('29','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('30','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('31','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('32','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('33','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('34','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('35','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('36','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('37','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('38','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('39','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('40','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('41','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('42','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('43','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('44','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('45','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('46','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('47','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('48','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('49','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('50','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('51','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('52','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('53','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('54','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('55','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('56','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('57','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('58','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('59','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('60','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('61','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('62','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('63','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('64','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('65','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('66','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('67','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('68','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('69','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('70','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('71','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('72','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('73','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('74','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('75','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('76','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('77','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('78','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('79','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('80','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('81','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('82','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('83','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('84','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('85','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('86','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('87','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('88','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('89','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('90','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('91','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('92','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('93','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('94','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('95','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('96','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('97','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('98','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('99','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('100','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('101','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');
INSERT INTO procedimento VALUES ('102','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip','The standard Lorem Ipsum passage, used since the 1500s');
INSERT INTO procedimento VALUES ('103','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi','Section 1.10.32 of "de Finibus Bonorum et Malorum"');
INSERT INTO procedimento VALUES ('104','But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('105','On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment','1914 translation by H. Rackham');
INSERT INTO procedimento VALUES ('106','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi','Section 1.10.33 of "de Finibus Bonorum et Malorum');